let listaDeCompras = [" pão", " leite", " ovos", " queijo", " frutas"];
console.log(listaDeCompras);
listaDeCompras.push(" café");
console.log(listaDeCompras);
listaDeCompras.unshift("manteiga");
console.log(listaDeCompras);
let itemRemovido = listaDeCompras.pop();
console.log(itemRemovido);
console.log(listaDeCompras);
let primeiroItemRemovido = listaDeCompras.shift();
console.log(primeiroItemRemovido);
console.log(listaDeCompras);
listaDeCompras.splice(1, 1, " chocolate" );
console.log(listaDeCompras);
listaDeCompras.splice(2, 1, " biscoitos", " suco" );
console.log(listaDeCompras);
let indice = listaDeCompras.indexOf(" frutas");
console.log(indice);
listaDeCompras.splice(5, 1 );
console.log(listaDeCompras);
